models:
  monkey:
    PRIVATE_monkeyModel:
      api_key: sk-sofhdjlkrdrg
      base_url: http://api.monkey.com/v1
      description: ''
      display_name: monkeyModel
      max_tokens: 64000
      model_id: mmodel-1.0.turbo
      provider: openai
      temperature: 0.7
  yuyang:
    PRIVATE_GLM-4.7-Flash:
      api_key: sk-xxxxxxx
      base_url: https://open.bigmodel.cn/api/paas/v4/
      description: GLM-4.7-Flash 作为 30B 级 SOTA 模型，提供了一个兼顾性能与效率的新选择。面向 Agentic Coding
        场景强化了编码能力、长程任务规划与工具协同，并在多个公开基准的当期榜单中取得同尺寸开源模型中的领先表现。在执行复杂智能体任务，在工具调用时指令遵循更强，Artifacts
        与 Agentic Coding 的前端美感和长程任务完成效率进一步提升。
      display_name: GLM-4.7-Flash
      max_tokens: 64000
      model_id: GLM-4.7-Flash
      provider: openai
      temperature: 0.7
